# =============================================================================
# API Gateway 운영 환경 설정 파일
# =============================================================================
# 운영 환경에서 사용되는 설정으로, 보안과 성능이 최적화되어 있습니다.
# 실행 방법: --spring.profiles.active=prod
# 
# 주의사항: 운영 환경에서는 반드시 환경 변수를 설정해야 합니다!
# - JWT_SECRET_KEY_PROD: JWT 서명용 비밀키 (필수)
# - *_SERVICE_URL: 각 서비스의 URL (선택, 기본값 사용 가능)

# 서버 설정
server:
  port: ${SERVER_PORT:8080}  # 운영 환경 포트

# Spring Cloud Gateway 설정
spring:
  cloud:
    gateway:
      # 라우팅 규칙 정의 (운영 환경용)
      routes:
        # =============================================================================
        # 사용자 관리 서비스 라우팅 (운영 환경)
        # =============================================================================
        - id: auth-service  # 인증 관련 라우트
          uri: ${USER_SERVICE_URL:http://user-service:8081}  # 환경 변수 또는 기본값
          predicates:
            - Path=/auth/**    # 인증 관련 API
        
        - id: user-service  # 사용자 관련 라우트
          uri: ${USER_SERVICE_URL:http://user-service:8081}  # 환경 변수 또는 기본값
          predicates:
            - Path=/user/**    # 사용자 관련 API

        # =============================================================================
        # 알림 서비스 라우팅 (운영 환경)
        # =============================================================================
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8082}  # 환경 변수 또는 기본값
          predicates:
            - Path=/noti/**    # 알림 관련 API


        # =============================================================================
        # 대시보드 서비스 라우팅 (운영 환경)
        # =============================================================================
        - id: dashboard-service
          uri: ${DASHBOARD_SERVICE_URL:http://dashboard-service:8083}  # 환경 변수 또는 기본값
          predicates:
            - Path=/home/**    # 대시보드 관련 API


        # =============================================================================
        # IoT 센서 서비스 라우팅 (운영 환경)
        # =============================================================================
        - id: sensors-service
          uri: ${SENSORS_SERVICE_URL:http://sensors-service:8084}  # 환경 변수 또는 기본값
          predicates:
            - Path=/sensors/**  # 센서 데이터 관련 API


        # =============================================================================
        # 리포트 서비스 라우팅 (운영 환경)
        # =============================================================================
        - id: report-service
          uri: ${REPORT_SERVICE_URL:http://report-service:8085}  # 환경 변수 또는 기본값
          predicates:
            - Path=/reports/**  # 리포트 관련 API


        # =============================================================================
        # 챗봇 서비스 라우팅 (운영 환경)
        # =============================================================================
        - id: chatbot-service
          uri: ${CHATBOT_SERVICE_URL:http://chatbot-service:8086}  # 환경 변수 또는 기본값
          predicates:
            - Path=/chatbot/**  # 챗봇 관련 API

# =============================================================================
# 로깅 설정 (운영 환경 - 최소 로깅)
# =============================================================================
logging:
  level:  # 운영 환경에서는 최소한의 로그만 출력 (성능 최적화)
    org.springframework.cloud.gateway: WARN  # Gateway 경고 로그만
    com.deefacto.api_gateway: INFO           # 애플리케이션 정보 로그
    org.springframework.web: WARN            # Web 경고 로그만
  pattern:  # 로그 출력 형식
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 콘솔 출력
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"     # 파일 출력
  file:  # 로그 파일 설정
    name: logs/api-gateway-prod.log  # 운영 환경 전용 로그 파일
    max-size: 100MB                  # 로그 파일 최대 크기 (운영 환경은 더 큰 용량)
    max-history: 90                  # 보관할 로그 파일 개수 (운영 환경은 더 오래 보관)

# =============================================================================
# Actuator 설정 (운영 환경 - 제한된 엔드포인트만 노출)
# =============================================================================
management:
  endpoints:  # 운영 환경에서는 보안을 위해 제한된 엔드포인트만 노출
    web:
      exposure:
        include: health,info,metrics  # 헬스 체크, 정보, 메트릭만 노출
      base-path: /actuator  # 기본 경로 설정
  endpoint:  # 엔드포인트별 설정
    health:
      show-details: when-authorized  # 인증된 사용자에게만 상세 정보 표시
    gateway:
      enabled: true  # Gateway 엔드포인트 활성화

# =============================================================================
# JWT 설정 (운영 환경 - 환경 변수 필수)
# =============================================================================
jwt:
  # 운영 환경용 JWT 시크릿 키 (환경 변수 필수 설정)
  # 보안상 하드코딩된 값 사용 금지!
  secret-key: ${JWT_SECRET_KEY_PROD}
  expires-in: 86400  # 토큰 만료 시간 (24시간) 