server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # 관리자 관리 서비스 라우팅
        - id: admin-service
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**
          # filters:
          #   - StripPrefix=1

        # 사용자 관리 서비스 라우팅
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          # filters:
          #   - StripPrefix=1

        # 알림 서비스 라우팅
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/noti/**
          # filters:
          #   - StripPrefix=1

        # 대시보드 관련 API 라우팅 (대시보드 페이지)
        - id: dashboard-service
          uri: http://localhost:8084
          predicates:
            - Path=/home/**
          # filters:
          #   - StripPrefix=1

        # IoT 센서 데이터 관리 서비스 라우팅
        - id: sensors-service
          uri: http://localhost:8085
          predicates:
            - Path=/sensors/**
          # filters:
          #   - StripPrefix=1

        # 리포트 서비스 라우팅
        - id: report-service
          uri: http://localhost:8086
          predicates:
            - Path=/reports/**
          # filters:
          #   - StripPrefix=2

        # 챗봇 서비스 라우팅
        - id: chatbot-service
          uri: http://localhost:8087
          predicates:
            - Path=/chatbot/**
          # filters:
          #   - StripPrefix=1

# 로깅 설정
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.deefacto.api_gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
    max-size: 10MB
    max-history: 30

# Actuator 설정 (모니터링용)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
